config/routes.rb
Rails.application.routes.draw do
  root                'sessions#new'
  get 'login'     =>  'sessions#new'
  post 'login'    =>  'sessions#create'
  delete 'logout' =>  'sessions#destroy'

  resources :users

  resources :quizzes do
    resources :invitations
    member do
      get 'start'
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name,  presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }, allow_blank: true
  has_many :quizzes
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user,    only: [:show, :edit, :update]
  before_action :examiner_user,   only: [:index, :new]
  before_action :admin_user,      only: [:destroy]

  def show
    @user = User.find_by_id(params[:id])
    @invitations = Invitation.where(email: @user.email)
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user, flash: { success: "Account was successfully created" }
    else
      render 'new'
    end
  end

  def edit
    @user = User.find_by_id(params[:id])
  end

  def update
    @user = User.find_by_id(params[:id])
    user = User.find_by_email(@user.email).try(:authenticate, params[:current_password])
    if user && @user.update_attributes(user_params)
      redirect_to @user, flash: { success: "Profile was successfully updated" }
    else
      flash[:danger] = "Please enter your current password"
      render 'edit'
    end
  end

  def destroy
    User.find_by_id(params[:id]).destroy
    redirect_to users_url, flash: { success: "User was successfully deleted" }
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% provide(:title, 'Update profile') %>
<h1>
  Update your profile
</h1>

<p>
  <%= link_to 'Back', :back %>
</p>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>

      <% if @user.errors.any? %>
        <div id="error_explanation">
          <div class="alert alert-danger">
            The form contains <%= pluralize(@user.errors.count, "error") %>.
          </div>
          <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <%= f.label :name %>*
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control', readonly: true %>

      <%= f.label "Current password" %>*
      <%= password_field_tag :current_password, params[:current_password], class: 'form-control' %>

      <%= f.label :password, "New password (minimum 6 characters)" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Retype new password" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.label "Fields marked with * are compulsory fields." %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>
  All users
</h1>

<p>
  <%= link_to 'Back', :back %>
  <% if current_user.admin? %>
    | <%= link_to 'New user', new_user_path %>
  <% end %>
</p>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <div class='col-md-3'>
        <%= link_to user.name, user %>
      </div>
      <% if current_user.admin? && user != current_user %>
        <div class='col-md-3'>
          <% unless user.examiner? %>
            <%= link_to "Make examiner", user, data: { confirm: "Make " + user.name + " an examiner?" } %> |
          <% else %>
            <%= link_to "Remove examiner", user, data: { confirm: "Remove " + user.name + " as examiner?" } %> |
          <% end %>
          <%= link_to "Edit", edit_user_path(user) %> |
          <%= link_to "DELETE", user, method: :delete, data: { confirm: "Delete " + user.name + "?" } %>
        </div>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'New user') %>

<h1>
  New user
</h1>

<p>
  <%= link_to 'Back', :back %>
</p>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>

      <% if @user.errors.any? %>
        <div id="error_explanation">
          <div class="alert alert-danger">
            The form contains <%= pluralize(@user.errors.count, "error") %>.
          </div>
          <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>

      <%= f.label :password, "Password (minimum 6 characters)" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Retype password" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1>
  <%= @user.name %>
</h1>

<p>
  <%= link_to 'Edit', edit_user_path(@user) %>
</p>

<p>
  <strong>Login:</strong> <%= @user.email %>
</p>

<% if current_user.admin? %>
  <p>
    <strong>Admin:</strong> <%= @user.admin? %>
  </p>
  <p>
    <strong>Examiner:</strong> <%= @user.examiner? %>
  </p>
<% end %>

<% if !@invitations.empty? %>
  Available quizzes:
  <br>
  <ul class='invitations'>
    <li>
      <strong>
        <div class='col-md-2'>
          Name
        </div>
        <div class='col-md-3'>
          Description
        </div>
        <div class='col-md-1'>
          Sender
        </div>
        <div class='col-md-2'>
          Invited
        </div>
        <div class='col-md-2'>
          Status
        </div>
        <% if current_user.examiner? %>
          <div class='col-md-1'>
            Submissions
          </div>
        <% end %>
      </strong>
    </li>
    <% @invitations.each do |invitation| %>
      <li>
        <div class='col-md-2'>
          <%= link_to invitation.quiz.name, invitation.quiz %>
        </div>
        <div class='col-md-3'>
          <%= invitation.quiz.description %>
        </div>
        <div class='col-md-1'>
          <%= invitation.sender_name %>
        </div>
        <div class='col-md-2'>
          <%= time_ago_in_words(invitation.created_at) %> ago
        </div>
        <div class='col-md-2'>
          <strong>
            <% if invitation.end_time.blank? %>
              NOT YET STARTED
            <% elsif Time.parse(invitation.end_time) <= Time.now %>
              ENDED
            <% else %>
              IN-PROGRESS
            <% end %>
          </strong>
        </div>
        <% if current_user.examiner? && invitation.quiz_answer.exists? %>
          <div class='col-md-1'>
            <%= link_to 'Download', invitation.quiz_answer.url %>
          </div>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>