config/routes.rb
Rails.application.routes.draw do
  root                'sessions#new'
  get 'login'     =>  'sessions#new'
  post 'login'    =>  'sessions#create'
  delete 'logout' =>  'sessions#destroy'

  resources :users

  resources :quizzes do
    resources :invitations
    member do
      get 'start'
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
  <![endif]-->
</head>
<body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "2359 Media", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav pull-right">
            <% if logged_in? %>
            <li>
              <%= link_to "Profile", current_user %>
            </li>
            <% if current_user.admin? || current_user.examiner? %>
              <li class="divider"></li>
              <li>
                <%= link_to "All users", users_path %>
              </li>
              <li>
                <%= link_to "All quizzes", quizzes_path %>
              </li>
            <% end %>
            <li class="divider"></li>
            <li>
              <%= link_to "Log out", logout_path, method: "delete" %>
            </li>
            <% else %>
              <li>
                <%= link_to "Log in", login_path %>
              </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <footer class="footer">
        <small>
          2359 Media Pte Ltd
        </small>
      </footer>
      <br>
      <%= debug(params) if Rails.env.development? %>
    </div>
</body>
</html>